### ISSUE TITLE
"error generating asdf cached envrc" when entering a specific directory

### ISSUE THREAD

**Issue by Mellbourn** [asdf-community/asdf-direnv#108]
I have got `asdf-direnv` working well in all cases except one. 
There are many folders with `direnv` functionality, where it works fine.
For instance, it works in the root of one of my projects, let's call it `feature`. 
But `feature` has one subdirectory, `clients` where it consistently fails if I jump to that folder from outside the project.

When I enter it, I get this output
```
> cd feature/clients
direnv: using asdf
direnv: Creating env file /Users/klas.mellbourn/.cache/asdf-direnv/env/1726223876-2621464125-2607174882-605883556
direnv: asdf plugin not installed: nodejs
direnv: Error generating asdf cached envrc
```
Note that first doing `cd feature` and _then_ doing `cd clients` works with no error. `cd clients` does not give any output in that scenario.

The error also occur if I cd from outside the project directly to one of the subdirectories of `clients`. E.g. `cd feature/clients/packages`.

There is no file named `/Users/klas.mellbourn/.cache/asdf-direnv/env/1726223876-2621464125-2607174882-605883556`

I found https://github.com/asdf-community/asdf-direnv/issues/102, but this is different. Setting the `ASDF_DIR` environment variable does not help.

I've tested deleting all the content of `.cache/asdf-direnv/env` and `.local/share/direnv/allow/` but it made no difference (except that I had to do `direnv allow` again, of course)

The fact that the error mentions `nodejs` is interesting. Previously I let `asdf` handle node versions, but to follow project standards, I had to switch to [volta](https://docs.volta.sh/) for handling node versions (I could still keep using `asdf` for other programming languages). So I have done `asdf plugin remove nodejs` recently.

Output of `asdf info`:
```
> asdf info
OS:
Darwin HKABCF7Y13 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

SHELL:
zsh 5.8.1 (arm-apple-darwin21.3.0)

ASDF VERSION:
v0.9.0-9ee24a3

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/klas.mellbourn/.asdf

ASDF INSTALLED PLUGINS:
bundler                      git@github.com:jonathanmorley/asdf-bundler.git master a461ac4
direnv                       git@github.com:asdf-community/asdf-direnv.git master ee6f68c
python                       git@github.com:danhper/asdf-python.git master 57a4d72
ruby                         git@github.com:asdf-vm/asdf-ruby.git master de49662
```

**Comment by jfly** [comment]
@Mellbourn, this feels like you've still got a `feature/clients/.tool-versions` file that mentions nodejs. Is that possible?

**Comment by Mellbourn** [comment]
Doh! That was it. Embarrassing. Thanks for the quick response!
