### ISSUE TITLE
Unable to find the actual executable installed by a package manager inside a project root 

### ISSUE THREAD

**Issue by yang-l** [asdf-community/asdf-direnv#117]
I am not sure if this is a bug or by design. I have followed the [setup](https://github.com/asdf-community/asdf-direnv#setup), and everything is working except this one, which is unable to find the actual executable inside a project root with a different version than defined at the HOME level.

Let's say there is a `.tool-versions` at the HOME level

```
$ cat ~/.tool-versions
nodejs 16.13.2
direnv 2.29.0
```
, and there is a list of packages installed by default for each nodejs version installed by `asdf` defined in `.default-npm-packages`
```
$ cat ~/.default-npm-packages
yarn
bash-language-server
dockerfile-language-server-nodejs
typescript-language-server
typescript
vscode-json-languageserver
```
There is a global level `.envrc` at the HOME level
```
$ cat ~/.envrc
use asdf
```

At the HOME level, `asdf-direnv` is able to find the actual executable
```
$ which -a yarn
/Users/yangliu/.asdf/installs/nodejs/16.13.2/.npm/bin/yarn
/Users/yangliu/.asdf/shims/yarn

$ which -a bash-language-server
/Users/yangliu/.asdf/installs/nodejs/16.13.2/.npm/bin/bash-language-server
/Users/yangliu/.asdf/shims/bash-language-server
```

However, if inside a project root, which is having a project level .envrc
```
~/tmp/direnv-test $ cat .envrc
use asdf
```
, and it has a different nodejs version, specified in `.node-version`
```
~/tmp/direnv-test $ cat .node-version
16.14.2
```

And by now, it is unable to find the actual executable for the default installed packages
```
~/tmp/direnv-test $ which -a yarn
/Users/yangliu/.asdf/shims/yarn

~/tmp/direnv-test $ which -a bash-language-server
/Users/yangliu/.asdf/shims/bash-language-server
```

Because there is a difference between nodejs versions, and I am unable to run the default installed packages even `asdf` recognise the correct nodejs version, such as

```
~/tmp/direnv-test $ yarn
No preset version installed for command yarn
Please install a version by running one of the following:

asdf install nodejs 16.14.2

or add one of the following versions in your config file at /Users/yangliu/.tool-versions
nodejs 14.18.1
nodejs 16.11.1
nodejs 12.22.7
nodejs 14.15.0
nodejs 16.4.2
nodejs 16.13.2

~/tmp/direnv-test $ asdf current
awscli          2.3.2           /Users/yangliu/.tool-versions
direnv          2.29.0          /Users/yangliu/.tool-versions
golang          1.17.2          /Users/yangliu/.tool-versions
kubectl         1.22.3          /Users/yangliu/.tool-versions
nodejs          16.14.2         /Users/yangliu/tmp/direnv-test/.node-version
python          3.10.0          /Users/yangliu/.tool-versions
ruby            2.7.4           /Users/yangliu/.tool-versions
terraform       ______          No version is set. Run "asdf <global|shell|local> terraform <version>"
```

I believe it should find the actual executable for the nodejs `16.14.2` version, e.g. `/Users/yangliu/.asdf/installs/nodejs/16.14.2/.npm/bin/yarn` and `/Users/yangliu/.asdf/installs/nodejs/16.13.2/.npm/bin/bash-language-server`

I might be able to add multiple versions of nodejs into the HOME level `.tool-versions` file, but I'd prefer to no mess up that file.

If I am not specifying a different nodejs version, `direnv` would resolve the `16.13.2` ones without a problem inside the project folder.

I am using zsh, and here are some information
```
~/tmp/direnv-test $ asdf info
OS:
Darwin Yang-Liu 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin21.2.0)

ASDF VERSION:
v0.9.0-9ee24a3

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/yangliu/.asdf

ASDF INSTALLED PLUGINS:
awscli                       https://github.com/MetricMike/asdf-awscli.git main ec4ccdc
direnv                       https://github.com/asdf-community/asdf-direnv.git master 016325f
golang                       https://github.com/kennyp/asdf-golang.git master cc8bc47
kubectl                      https://github.com/Banno/asdf-kubectl.git master 11ac5c3
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git master f9957f3
python                       https://github.com/danhper/asdf-python.git master 57a4d72
ruby                         https://github.com/asdf-vm/asdf-ruby.git master de49662
terraform                    https://github.com/asdf-community/asdf-hashicorp.git master aeff16f
```

```
~/tmp/direnv-test $ direnv status
direnv exec path /Users/yangliu/.asdf/installs/direnv/2.29.0/bin/direnv
DIRENV_CONFIG /Users/yangliu/.config/direnv
bash_path /bin/bash
disable_stdin false
warn_timeout 5s
whitelist.prefix []
whitelist.exact map[]
Loaded RC path /Users/yangliu/tmp/direnv-test/.envrc
Loaded watch: ".envrc" - 2022-03-24T10:00:07+13:00
Loaded watch: "../../.local/share/direnv/allow/817acd8e478f91c89718cb7dddd4c048b99500836cdd5396a3669e767d34c13d" - 2022-03-24T09:58:07+13:00
Loaded watch: "../../.cache/asdf-direnv/env/130169932-968353120-2692163941-3328304145" - 2022-03-24T10:00:08+13:00
Loaded watch: "../../.tool-versions" - 2022-03-24T09:30:04+13:00
Loaded watch: "../../.asdf/plugins/ruby/bin/exec-env" - 2021-05-23T19:46:28+12:00
Loaded watch: "../../.asdf/plugins/nodejs/bin/exec-env" - 2021-05-30T20:49:36+12:00
Loaded watch: ".node-version" - 2022-03-24T09:59:42+13:00
Loaded watch: "../../.asdf/plugins/golang/bin/exec-env" - 2022-03-23T14:07:40+13:00
Loaded RC allowed false
Loaded RC allowPath
Found RC path /Users/yangliu/tmp/direnv-test/.envrc
Found watch: ".envrc" - 2022-03-24T10:00:07+13:00
Found watch: "../../.local/share/direnv/allow/817acd8e478f91c89718cb7dddd4c048b99500836cdd5396a3669e767d34c13d" - 2022-03-24T09:58:07+13:00
Found RC allowed true
Found RC allowPath /Users/yangliu/.local/share/direnv/allow/817acd8e478f91c89718cb7dddd4c048b99500836cdd5396a3669e767d34c13d
```

Thanks

**Comment by jfly** [comment]
@yang-l, this is by design. I believe you'll find the same behavior even with plain old asdf without direnv. asdf does a really good job of keeping things *isolated*, and I don't think it has any support for simultaneously having 2 versions of the same tool activated at the same time.

What follows below is a philosophical ramble that you may or may not find useful.
<hr>

I prefer to keep nothing in my top level `~/.tool-versions` file (except for asdf-direnv itself), in favor of keeping everything in project specific `.tool-versions` files. It's a little more work up front, but gets you closer to having a self-contained project that other developers (or future me with a new laptop) can hack on with minimal hassle. So I personally don't put anything in my `~/.tool-versions` file, and instead strive to put everything I need in my individuali project's `~/.tool-versions` files.

However, that may sound pretty silly/impossible: what about something like vim, or maybe `bash-language-server`? They aren't really part of my project, so I choose to install that sort of stuff using my system's package manager. Maybe that's a reasonable option for you with some of these things?

**Comment by yang-l** [comment]
Thanks, fair enough. Very useful comments, and I will try to adjust my workflow a little bit.
