### ISSUE TITLE
bug: "Cleanup: Something went wrong!" when installing new version

### ISSUE THREAD

**Issue by Mellbourn** [asdf-community/asdf-direnv#119]
### Describe the Bug

I have direnv 2.30.3 installed with asdf, works fine.

If I try to install the latest direnv, it reports an error.

### Steps to Reproduce

1. `asdf install direnv latest`

OR

1. `asdf install direnv 2.31.0`

### Expected Behaviour

```
∗ Downloading and installing direnv...
The installation was successful!
```

### Actual Behaviour

```
❯ asdf install direnv latest
∗ Downloading and installing direnv...

Cleanup: Something went wrong!

61 /Users/klas.mellbourn/.asdf/plugins/direnv/bin/install: curl --fail --silent --location --create-dirs --output "$source_path" "$download_url"
```

The result is that direnv is not updated.

I tested manually uninstalling direnv 2.30.3, but that did not help.
I tested manually removing the direnv plugin, and adding it again, but that did not help.
The version specific command `asdf install direnv 2.30.3` works.

### Debug Output

```shell
env ASDF_DIRENV_DEBUG=true direnv reload
direnv: error .envrc not found
```

**Comment by smorimoto** [comment]
It seems that there are no release assets. It's more of an upstream issue.
https://github.com/direnv/direnv/releases/tag/v2.31.0

**Comment by jfly** [comment]
For the record, here's the relevant issue upstream: https://github.com/direnv/direnv/issues/912

**Comment by vic** [comment]
@Mellbourn, could you please try again. I believe the upstream issue has been fixed now.

**Comment by Mellbourn** [comment]
Yes, this is fixed for me now. Thanks!
