### ISSUE TITLE
Why do we instruct people to install asdf as a shell function rather than just getting the asdf binary on their PATH?

### ISSUE THREAD

**Issue by jfly** [asdf-community/asdf-direnv#124]
Our [pro tips](https://github.com/asdf-community/asdf-direnv#pro-tips) teach people to get the ASDF shims out of their PATH. That's great, but I find this part strange:

    source "~/.asdf/lib/asdf.sh" # just load the asdf wrapper function

Why do we instruct people to set up the wrapper function? AFAIK, the only reason you'd want `asdf` as a wrapper function would be for `asdf shell` to be able to set some environment variables that affect shim behavior (note how `asdf shell` is the *only* command that does anything other than just invoking the asdf script: https://github.com/asdf-vm/asdf/blob/7493f4099c844e40af72d7f05635d7991a463d1a/lib/asdf.sh#L10). But shims don't even work if you're a pro asdf-direnv use and have removed the asdf shims directory form your PATH!

I personally have been running asdf-direnv for a while with no shims and no shell function, I haven't had any issues. (this wasn't an intentional misconfiguration on my part, I think I just never saw the "pro tips" until recently)

(side note: I'm pretty sure the instructions are actually broken... I don't think `~` does what we want when inside of double quotes like that)

**Comment by michi-zuri** [comment]
I agree 👍🏿 

I've been running asdf-direnv with this in my .bashrc and also haven't encountered any problems:
```
PATH=~/.asdf/bin:$PATH:/home/killian/.asdf/shims
. $HOME/.asdf/completions/asdf.bash
eval "$(asdf exec direnv hook bash)"
direnv() { asdf exec direnv "$@"; }
```

**Comment by vic** [comment]
Feel free to send a PR to improve those sections :)

**Comment by jfly** [comment]
I think we can close this now that `asdf direnv setup` exists, and it doesn't set up the `asdf` shell function =)

Thanks, @vic!
