### ISSUE TITLE
`asdf direnv setup zsh` leaves my zshrc in a different state than the manual instructions

### ISSUE THREAD

**Issue by jfly** [asdf-community/asdf-direnv#125]
I'm just catching up on all the awesome work that has happened since last week.

I tried out `asdf direnv setup zsh`, and here's what happened:

```
$ echo $ASDF_DIRENV_BIN

$ asdf direnv setup zsh
Checking for asdf...
✔️  Found asdf at /home/jeremy/.asdf/bin/asdf
Checking for direnv...
✔️  Found direnv at /home/jeremy/.asdf/installs/direnv/2.30.3/bin/direnv
Checking for direnv shell integration...
✍  Modifying /home/jeremy/.zshrc ✔️
Checking for direnv asdf integration...
✍  Modifying /home/jeremy/.config/direnv/lib/use_asdf.sh ✔️

$ tail -n 2 ~/.zshrc
export ASDF_DIRENV_BIN="/home/jeremy/.asdf/installs/direnv/2.30.3/bin/direnv"
eval "$(/home/jeremy/.asdf/installs/direnv/2.30.3/bin/direnv hook zsh)"
```

Note how the exact path and version of direnv shows up here, whereas our [manual steps in the README](https://github.com/asdf-community/asdf-direnv#setup) tell you to do something like:

```
export ASDF_DIRENV_BIN="$(asdf which direnv)" # or `$(command -v direnv)` for system managed.

# Hook direnv into your shell.
eval "$($ASDF_DIRENV_BIN hook bash)"
```

Is this discrepancy intentional, @vic?

**Comment by vic** [comment]
Yep, it's intentional. The `setup` command does either `command -v direnv` / `asdf which direnv` and just places the resolved binary path directly in your rc-file, instead of resolving again each time.  (eg, `asdf which direnv` probably does asdf version resolution each time you open a new shell)

**Comment by vic** [comment]
We should perhaps improve the manual instructions instead.

**Comment by vic** [comment]
Or is it better to remove the manual sections ? I guess I leaved them there for reference, but ideally unless the `setup` command fails very badly, people should not have to bother with manual setup.
