### ISSUE TITLE
Bug: `asdf direnv setup` does not respect `$ZDOTDIR`

### ISSUE THREAD

**Issue by SanchithHegde** [asdf-community/asdf-direnv#135]
### Describe the Bug

When `asdf direnv setup` is run with the environment variable `$ZDOTDIR` pointing to anything other than `$HOME`, the command writes to `$HOME/.zshrc` instead of `$ZDOTDIR/.zshrc`, which is where the user has configured `zsh`.

### Steps to Reproduce

1. Set `$ZDOTDIR` to anything other than `$HOME`, say `$HOME/.config/zsh`.
   ```shell
   export ZDOTDIR=$HOME/.config/zsh
   ```
2. Run `asdf direnv setup --shell zsh --version latest`.

### Expected Behaviour

`asdf direnv setup` command writes to `$ZDOTDIR/.zshrc`.

### Actual Behaviour

`asdf direnv setup` command writes to `$HOME/.zshrc` instead of `$ZDOTDIR/.zshrc`.

### Debug Output

```shell
N/A
```

---

To be precise, just this line needs to be updated to fix this. I'm not sure if there's a similar environment variable for `bash` though.

https://github.com/asdf-community/asdf-direnv/blob/9c1f1e6d63b11d19b21ec3018662c09fa1b14571/lib/setup-lib.bash#L152

From the `zsh` [manual page](https://man.archlinux.org/man/extra/zsh/zsh.1.en#STARTUP/SHUTDOWN_FILES):

> ... if the shell is interactive, commands are read from `/etc/zshrc` and then `$ZDOTDIR/.zshrc`.
> ...
> If `ZDOTDIR` is unset, `HOME` is used instead.

**Comment by jfly** [comment]
This was fixed by #137
