### ISSUE TITLE
Change `asdf direnv setup` to detect if direnv is already set up

### ISSUE THREAD

**Issue by jfly** [asdf-community/asdf-direnv#140]
Right now, if someone *already* is a direnv user, and they follow our instructions to install `asdf-direnv`, they're going to find that their shell sets up the direnv shell hook twice. We should see what we can do about that: perhaps we can detect if it has already happened and skip doing it ourselves?

(This spun out of this discussion: https://github.com/asdf-community/asdf-direnv/issues/134)

**Comment by vic** [comment]
Here are the functions that are defined by direnv when you hook it into your shell

bash: [`_direnv_hook`](https://github.com/direnv/direnv/blob/master/internal/cmd/shell_bash.go#L11)
fish: [`__direnv_export_eval`](https://github.com/direnv/direnv/blob/master/internal/cmd/shell_fish.go#L14)
zsh: [`_direnv_hook`](https://github.com/direnv/direnv/blob/master/internal/cmd/shell_zsh.go#L10)

**Comment by vic** [comment]
Looking at the hooks linked above, I believe there's no problem on doing `direnv hook` more than once, since direnv checks and will add the hook only if not present (from what I can read in their code).

**Comment by jfly** [comment]
Thanks for investigating, @vic! Where does direnv check if the hook is already added? I'm not immediately seeing it in the code you linked to above.

**Comment by vic** [comment]
hooks are those functions (particular by shell) that get added to prompt function, there's s check on each of them not to add if they are already present.

**Comment by jfly** [comment]
Oh, I see it now! Then I think we can close this out =)
