### ISSUE TITLE
bug: Unknown command: asdf direnv _asdf_cached_envrc

### ISSUE THREAD

**Issue by pikeas** [asdf-community/asdf-direnv#146]
### Describe the Bug

```
$ asdf info

OS:
Darwin abp22.lan 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

SHELL:
fish, version 3.3.1

ASDF VERSION:
v0.9.0

ASDF ENVIRONMENT VARIABLES:
ASDF_DIRENV_BIN=/opt/homebrew/bin/direnv
ASDF_DEFAULT_TOOL_VERSIONS_FILENAME=/Users/pikeas/.config/asdf/tool-versions

ASDF INSTALLED PLUGINS:
direnv                       ssh://git@github.com/asdf-community/asdf-direnv.git master 23948c4
[others]
```

I do *not* have `~/.asdf/shims` on my PATH. 
I do *not* have `~/.asdf/bin` on my PATH (listed under pro tips), because this directory doesn't exist. 

`ASDF_DIR` is *not* set. I've tried setting it, but that seems to break things in different ways. There's a new release of ASDF coming soon per https://github.com/asdf-vm/asdf/pull/1111, this may be related to some of these errors. 

I'd love to get things working under the current 0.9.0 release, please let me know what I should try next!

### Steps to Reproduce

cd into a directory with `.envrc` that calls `use asdf`.

### Expected Behaviour

No errors.

### Actual Behaviour

Same as debug output below.

### Debug Output

```shell
command: `asdf direnv _asdf_cached_envrc`
No documentation for plugin direnv
```

**Comment by vic** [comment]
Hey @pikeas, looks like you had an old asdf-direnv version, please update this plugin an run `asdf direnv setup` (see the README for instructions on this). Also, be sure to remove the old `use_asdf` function from your `~/.config/direnv/direnvrc`, our new setup command will now create that function under `~/.config/direnv/lib/use_asdf.sh` leaving the former untouched.

**Comment by pikeas** [comment]
Great catch on the old plugin version! I've now added `asdf plugin-update --all` to my monthly update script as well.

Everything now seems to be working as intended (not sourcing `asdf.sh`, shims not on PATH, and `ASDF_DIR` is unset).
