### ISSUE TITLE
bug: Duplicate plugin bin paths due to exec-env adding to PATH

### ISSUE THREAD

**Issue by ericem** [asdf-community/asdf-direnv#148]
### Describe the Bug

When I `use asdf` with the  [asdf-ruby](https://github.com/asdf-vm/asdf-ruby), I get the ruby plugin's bin path added twice to the the PATH environment variable. The bin PATH is added once in the [ruby exec-env](https://github.com/asdf-vm/asdf-ruby/blob/a1352b4454fe8f414a786f90f7311a09624b9fbc/bin/exec-env#L13) file and a second time by [asdf-direnv tools-environment-lib.bash](https://github.com/asdf-community/asdf-direnv/blob/7185c66cbc63fbfce8f8f8008c63c133437a1119/lib/tools-environment-lib.bash#L292). The `_plugin_env_bash` function in tools-environment-lib.bash uses the asdf helper `list_plugin_bin_paths`, however, the ruby plugin does not include a  the `list-bin-paths` command, which the helper uses to generate the list of bin paths. I can file an issue with asdf-ruby to include a `list-bin-paths` command, but asdf-direnv could also de-dup the paths before adding the with PATH_add. This would mean the call to the plugins `exec-env` would need to happen before the PATH_add. I'm not sure if that would be and issue.

asdf version: 0.9.0
asdf-direnv version: 0.3.0
asdf-ruby version: master/a1352b4454fe8f414a786f90f7311a09624b9fbc

### Steps to Reproduce

1. `brew install asdf`
2. `brew install direnv`
3. `asdf plugin add asdf-direnv`
4. Create a .tool-versions with:

```
ruby 2.7.4
```

5. Check the PATH `echo $PATH`, and verify that `asdf/installs/ruby/2.7.4/bin/` is included twice.

### Expected Behaviour

The PATH environment variable should only include the ruby plugin bin path once.

### Actual Behaviour

PATH includes asdf/installs/ruby/2.7.4/bin twice.

### Debug Output

```shell
direnv: loading $SRC_HOME/test/.envrc
direnv: using asdf
direnv: Creating env file $HOME/.cache/asdf-direnv/env/3567189093-2382350711-599017699-1219248241
direnv: loading $HOME.cache/asdf-direnv/env/3567189093-2382350711-599017699-1219248241
direnv: using asdf ruby 2.6.3
direnv: loading $BUILD_HOME/asdf/plugins/ruby/bin/exec-env
direnv: export +RUBYLIB ~PATH ~XPC_SERVICE_NAME
```

**Comment by vic** [comment]
I believe this should be fixed in `asdf-ruby`. It's strange that they set `PATH` in `exec-env` given that asdf-core only appends it's own shims into PATH and does not rely on any other PATH modifications.

The only useful case where that PATH modification would make sense to me is the `asdf-ruby` is trying to bypass asdf shims (perhaps because of speed). Since `exec-env` produces the environment as it should be available for executables, running eg, `gem` would make the underlying ruby process to find `$ASDF_INSTALL_PATH/bin` before all PATH (including asdf shims) - that is, having direct access to their executables.

**Comment by vic** [comment]
I'm closing this one, since I don't think we need to de-dup nor alter environment variables exposed by plugin's `exec-env`.

**Comment by vic** [comment]
@ericem Can you elaborate on how that `exec-env` PATH modification is causing a problem for you? Is anything not working?

I'd like to know others opinion on this and if we can find something actionable on this repo. @jfly, I believe you use `asdf-ruby` right ?

**Comment by jfly** [comment]
I actually was aware of this issue, but couldn't think of how to fix it :(

If you dig through the `asdf-ruby` history, you'll find that this behavior was added in this PR: https://github.com/asdf-vm/asdf-ruby/pull/26, which fixed the issue described in this comment: https://github.com/asdf-vm/asdf/issues/64#issuecomment-261809489

Basically, a command command like `ruby -S irb` actually searches your PATH hoping to find a ruby script named `irb`. If instead it finds a shell script, it spits out some error message about not being able to find the ruby script.

IMO, this is yet another reason why shims suck, haha.

Unfortunately, even though this workaround wouldn't be necessary with asdf-direnv, it *is* necessary with vanilla asdf. I'm not sure if asdf itself provides a better mechanism to achieve their goals. If not, one wild idea would be for *us* to provide some boolean that asdf plugin authors could use to check if they're running inside vanilla asdf vs asdf-direnv? But urg that sounds like a mess, and maybe it would just be better for us to dedupe the PATH.

**Comment by vic** [comment]
@jfly no, because [we no longer use asdf's `with_plugin_env`](https://github.com/asdf-community/asdf-direnv/commit/6ac3b571f702ec04704090cd92b42aa56e93f2ea)

**Comment by vic** [comment]
> But urg that sounds like a mess, and maybe it would just be better for us to dedupe the PATH.

I'd like no to mess with touching plugin's variables, we do prepend bin-paths using direnv's `PATH_add` but then simply source the plugin's `exec-env` expecting *it* to be responsible for setting the correct extra environment.

IMHO this should be fixed in `asdf-ruby`, and have their `exec-env` prepend their `<install-dir>/bin` only not already in `PATH`.

**Comment by jfly** [comment]
Ooh, is it possible that asdf-core has changed since the asdf-ruby folks introduced their PATH workaround, and that workaround isn't necessary anymore?

**Comment by vic** [comment]
quite possible, I believe asdf [do remove shims prior execution](https://github.com/asdf-vm/asdf/blob/master/lib/utils.bash#L756)

**Comment by vic** [comment]
> Ooh, is it possible that asdf-core has changed since the asdf-ruby folks introduced their PATH workaround, and that workaround isn't necessary anymore?

looks like you are right, see https://github.com/asdf-vm/asdf-ruby/pull/265#issuecomment-1100117455

**Comment by vic** [comment]
> If not, one wild idea would be for _us_ to provide some boolean that asdf plugin authors could use to check if they're running inside vanilla asdf vs asdf-direnv?

Just as an side-note, according to `direnv stdlib` there's already a way to check if code is running inside an envrc, checking for non empty `$DIRENV_IN_ENVRC`:

```
# This variable can be used by programs to detect when they are running inside
# of a .envrc evaluation context. It is ignored by the direnv diffing
# algorithm and so it won't be re-exported.
export DIRENV_IN_ENVRC=1
```
