### ISSUE TITLE
`direnv: error invalid line` when environment variables start with a newline character

### ISSUE THREAD

**Issue by jfly** [asdf-community/asdf-direnv#15]
I have my `TIMEFMT` environment variable set as so:

```
###
### Fix output of time to look more like bash.
### See https://superuser.com/a/71890.
###
export TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'
```

This causes problems here: https://github.com/asdf-community/asdf-direnv/blob/110164014a950be78e53c4d66d918c6684f279bc/shims/direnv_use_asdf#L124

```bash
$ asdf exec direnv dotenv bash <(env)
direnv: error invalid line: real	%E
```

I guess this is because the output of `env` is not a valid `.env` file format ([relevant validation here](https://github.com/direnv/direnv/blob/1456c6c4a5794c56b2908413b818fed4f6a4a798/vendor/github.com/direnv/go-dotenv/parse.go#L48)).

Unfortunately, I don't understand enough about what the purpose of this `_plugin_env` function is in order to suggest a fix. Are we just trying to capture the updated `PATH` environment variable? Maybe we should just be looking at that?

**Comment by imbsky** [comment]
@all-contributors please add @jfly for bug

**Comment by jfly** [comment]
Thanks for the quick response and fix!
