### ISSUE TITLE
bug: direnv setup fails to setup shell on fresh install

### ISSUE THREAD

**Issue by shawn1368** [asdf-community/asdf-direnv#154]
### Describe the Bug

After a fresh install of asdf and asdf-direnv per the instructions at https://asdf-vm.com/guide/getting-started.html and https://github.com/asdf-community/asdf-direnv#setup, running `asdf direnv setup --shell bash --version latest` fails.

This is on Fedora 36, bash.

### Steps to Reproduce

```
$ asdf plugin-add direnv
initializing plugin repository...Cloning into '/home/huaen/.asdf/repository'...
remote: Enumerating objects: 4041, done.
remote: Counting objects: 100% (1010/1010), done.
remote: Compressing objects: 100% (200/200), done.
remote: Total 4041 (delta 861), reused 883 (delta 809), pack-reused 3031
Receiving objects: 100% (4041/4041), 890.11 KiB | 3.48 MiB/s, done.
Resolving deltas: 100% (2109/2109), done.
$ asdf direnv setup --shell bash --version latest
Checking for asdf...
✔️  Found asdf at /home/huaen/.asdf/bin/asdf
Checking for direnv...
▶ asdf install direnv latest # ...  ∗ Downloading and installing direnv...
The installation was successful!
✔️
▶ env ASDF_DIRENV_VERSION=*2.32.1 asdf which direnv # ...  No preset version installed for command direnv
Please install a version by running one of the following:

asdf install direnv *2.32.1

or add one of the following versions in your config file at /home/huaen/.tool-versions
direnv 2.32.1
❗️ Failed with status 1
❌  No direnv executable found
```

### Expected Behaviour

The `direnv setup` command should have set up .bashrc correctly, without producing any errors.

### Actual Behaviour

The `direnv setup` command failed to set up .bashrc correctly.

### Debug Output

```shell
$ env ASDF_DIRENV_DEBUG=true direnv reload
direnv: error .envrc not found
```

**Comment by jfly** [comment]
> If the version of direnv is set to latest in asdf

@shawn1368, what does this mean? Are you referring to the contents of a `.tool-versions` file somewhere?

**Comment by shawn1368** [comment]
I'm referring to the global `$HOME/.tool-versions`. 

If the global version of direnv is set to `latest` in ASDF-vm via `asdf global direnv latest` before `asdf direnv setup` is run, this will cause `asdf list direnv` to show the latest version as `*latest_version_number`, thus causing the code above to fail. A possible fix is to remove the asterisk to ensure that this does not occur.

**Comment by jfly** [comment]
Ahhh, got it. You didn't mention that step in your original instructions.

It looks like this was fixed in https://github.com/asdf-community/asdf-direnv/commit/8f0746eb48ebc0984cadb47e0997baa8db7b649a.

Thanks for the bug report!
