### ISSUE TITLE
Upgrading direnv shouldn't require modifying my *shrc file

### ISSUE THREAD

**Issue by geoelectric** [asdf-community/asdf-direnv#166]
### Describe the Bug

If I understand correctly, one must currently execute `asdf direnv setup --shell zsh --version latest` each time one updates `direnv` from within `asdf`.

This does two things, one of which is desirable and one isn't:

1) It modifies the config under `.config/asdf-direnv/zshrc` (or wherever) to set the `ASDF_DIRENV_BIN` dir to that version of direnv. This file is also responsible for calling the hook. This is desirable, at least to the point feeding it the specific version of direnv is desirable (strikes me as a second point of truth to asdf, requiring this extra step, but I'm sure there's an optimization related reason it's done that way).
2) It modifies the active `.zshrc` to source the asdf-direnv zshrc by adding the line `source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"` at the end. It does this every time setup is called unless it finds that exact text somewhere in the zshrc file. This is *not* desirable.

Basically, we're forced to choose between never updating direnv, having to edit our rc file every time we update, or to let this plugin dictate the syntax of that call. This prevents, for example, putting that source call into a zsh plugin, which is how I otherwise manage both asdf and asdf-direnv, or removing the (in my case unnecessary) default to `~/.config` in the `XDG_CONFIG_HOME` variable that I explicitly set on my system.

There's already a versioning abstraction in the `.config/asdf-direnv/zshrc` file by way of the `BIN` env variable. That's all that ever needs to change for an upgrade. Once I've set up the call to that file from my own init files, nothing ever needs to change how I do that.

Either the act of upgrading asdf-direnv should have its own upgrade command that skips the `~/.zshrc` modification step, or setup should have some way to say don't update my main config.

### Steps to Reproduce

1. Install asdf-direnv
2. `asdf-direnv setup --shell zsh --version latest`
3. observe `~/.zshrc` is changed. Change the last line (the sourcing of the asdf-direnv zshrc) to use `.` instead of `source`
4. re-run the last setup command.
5. observe `~/.zshrc` is changed and now has two copies of the line, your modified and the original.

### Expected Behaviour

`~/.zshrc` changed on initial run, but not on subsequent ones.

### Actual Behaviour

`~/.zshrc` modified both times

### Debug Output

```shell
If you need this on followup I will, but should be easily reproducible without.
```

**Comment by geoelectric** [comment]
I suppose in retrospect, calling this a bug was awfully opinionated, but such was the direction the template guided me. I missed the tiny text saying I could also open a blank issue :)

Consider it a request for at least a discussion of change of behavior.

**Comment by jfly** [comment]
> strikes me as a second point of truth to asdf, requiring this extra step, but I'm sure there's an optimization related reason it's done that way

What's the other source of truth? Are you thinking about a `~/.tool-versions` file that mentions which "global" version of direnv to use?

You are right that this `ASDF_DIRENV_BIN` thing is a optimization. See https://github.com/asdf-community/asdf-direnv/issues/80 for details.

Some thoughts/ideas:

1. It sounds like all your problems go away if you used a system managed installation of direnv. You'd be able to run the setup script once and never again. Using a plugin managed direnv is kind of funky, and I've [advocated for removing it in the past](https://github.com/asdf-community/asdf-direnv/issues/134).
2. You could leave the line of code that the setup script wants in your zshrc but commented out.
3. We could add a new script, or a new parameter to the setup script (`--no-touch-rc-file`).

> ~/.zshrc changed on initial run, but not on subsequent ones.

@geoelectric, how would you achieve this? The only clue we have that we updated the `~/.zshrc` file is that line of code we added. If it's gone, then we have no idea if this is the first, second or 100th time you're running the setup script.

**Comment by geoelectric** [comment]
I’d lean towards the direction of providing two commands, with upgrade
being the one that skips the shell script. The software may not know, but
the user does.

Re: system, I agree. I fell back on that, but unfortunately the author of
the Zim plugin took your suggestion of removing the shims path—and aliases
direnv to `asdf exec direnv` if he detects your plugin.

The problem there is that asdf exec doesn’t seem to work with system
versions, so it’s effectively an incompatibility emergent from the combo of
projects.

That’s a different discussion, but a good example of why having more user
control than you’re allowing would be a good idea. Weird stuff happens.

**Comment by jfly** [comment]
@geoelectric, I'd accept a PR that adds a separate upgrade command if you want to send one in!
