### ISSUE TITLE
bug: setup instructions out of date?

### ISSUE THREAD

**Issue by fugkco** [asdf-community/asdf-direnv#184]
### Describe the Bug

Trying to set up asdf-direnv, and it seems the setup instructions might be out of date? direnv complains that the command `setup` doesn't exist. Looking at the help of the direnv binary seems to suggest that subcommand doesn't exist.

### Steps to Reproduce

```
$ asdf plugin-add direnv
updating plugin repository...remote: Enumerating objects: 1332, done.
remote: Counting objects: 100% (642/642), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 1332 (delta 633), reused 636 (delta 632), pack-reused 690
Receiving objects: 100% (1332/1332), 413.83 KiB | 3.13 MiB/s, done.
Resolving deltas: 100% (788/788), completed with 22 local objects.
From https://github.com/asdf-vm/asdf-plugins
   2bad31e..22e3806  master     -> origin/master
HEAD is now at 22e3806 feat: add regsync plugin (#882)
Plugin named direnv already added

$ asdf direnv setup --shell zsh --version latest
direnv: error command "/home/fugkco/.asdf/installs/direnv/2.28.0/bin/direnv setup" not found

$ /home/fugkco/.asdf/installs/direnv/2.28.0/bin/direnv --help
direnv v2.28.0
Usage: direnv COMMAND [...ARGS]

Available commands
------------------
allow [PATH_TO_RC]:
  Grants direnv to load the given .envrc
deny [PATH_TO_RC]:
  Revokes the authorization of a given .envrc
edit [PATH_TO_RC]:
  Opens PATH_TO_RC or the current .envrc into an $EDITOR and allow
  the file to be loaded afterwards.
exec DIR COMMAND [...ARGS]:
  Executes a command after loading the first .envrc found in DIR
fetchurl <url> [<integrity-hash>]:
  Fetches a given URL into direnv's CAS
help [SHOW_PRIVATE]:
  shows this help
hook SHELL:
  Used to setup the shell hook
prune:
  removes old allowed files
reload:
  triggers an env reload
status:
  prints some debug status information
stdlib:
  Displays the stdlib available in the .envrc execution context
version [VERSION_AT_LEAST]:
  prints the version (2.28.0) or checks that direnv is older than VERSION_AT_LEAST.

```

### Expected Behaviour

¯\_ (ツ)_/¯

### Actual Behaviour

```
$ asdf direnv setup --shell zsh --version latest
direnv: error command "/home/fugkco/.asdf/installs/direnv/2.28.0/bin/direnv setup" not found
```

### Debug Output

```shell
N/A
```

**Comment by jfly** [comment]
Strange. I don't know what's wrong here.

What do you see in the `PLUGIN` sections of `asdf --help`? For example, here's what happens on my machine:

```
$ asdf --help
...
PLUGIN direnv
  asdf direnv _asdf_cached_envrc
  asdf direnv envrc
  asdf direnv hook asdf
  asdf direnv local
  asdf direnv setup
  asdf direnv shell

PLUGIN nodejs
  asdf nodejs nodebuild
  asdf nodejs resolve
  asdf nodejs update nodebuild
```

Note how I have a number of `asdf direnv` subcommands, of which `setup` is just one.

> ```$ /home/fugkco/.asdf/installs/direnv/2.28.0/bin/direnv --help```

For the record, this command is irrelevant. The setup command is part of the asdf-direnv plugin (it's at `~/.asdf/plugins/direnv/lib/commands/command-setup.bash`), *not* part of direnv itself.

**Comment by fugkco** [comment]
Ah thanks for clarifying. Anyway, 

I only see the hook entry for direnv:

```
$ asdf --help
version: v0.10.2-7e7a1fa
...
PLUGIN direnv
  asdf direnv
  asdf direnv hook asdf

PLUGIN nodejs
...
```

**Comment by jfly** [comment]
Hmm... are you running an old version of the direnv plugin?

**Comment by fugkco** [comment]
My `~/.tools-version` was set to 2.28.0, not sure when I did that, but either way, I upgraded to the latest version `2.32.2` as per direnv's website, but still the same thing. 

```
$ asdf list direnv
  2.28.0
  2.32.2
$ asdf global direnv 2.32.2
$ asdf direnv setup --shell zsh --version latest
direnv: error command "/home/fugkco/.asdf/installs/direnv/2.32.2/bin/direnv setup" not found
```

Now that you mention that setup is part of asdf instead of direnv, I had a quick look. It certainly is running direnv itself using the setup argument. I added a printf statement (`printf ":%s:\n" "$direnv" "$@")` in the script:

```
+ printf ':%s:\n' /home/fugkco/.asdf/installs/direnv/2.32.2/bin/direnv setup --shell zsh --version latest
:/home/fugkco/.asdf/installs/direnv/2.32.2/bin/direnv:
:setup:
:--shell:
:zsh:
:--version:
:latest:
+ exec /home/fugkco/.asdf/installs/direnv/2.32.2/bin/direnv setup --shell zsh --version latest
```
Not sure what calls this script with the relevant arguments though.

Interestingly, this same command ran fine on my work computer.

**Comment by jfly** [comment]
@fugkco, that doesn't answer my question. I'm asking about the version of the plugin, *not* the version of direnv you're using this plugin to activate (this is a confusing and subtle difference, see https://github.com/asdf-community/asdf-direnv/discussions/92#discussioncomment-2327675 for an explanation). 

Try something like `asdf plugin list --refs`

**Comment by fugkco** [comment]
After reading your comment, I blindly did an update of all plugins, and now it's working, though I don't really understand why. Seems like it updated some things. It's weird why it didn't pull the latest version though, but then again, I don't know why I had direnv 2.28.0 installed previously. So all is good now!

```
$ asdf plugin-update --all
...
Updating direnv to master
From https://github.com/asdf-community/asdf-direnv
   375d161..6c109a3  master     -> master
   375d161..6c109a3  master     -> origin/master
 * [new tag]         v0.3.0     -> v0.3.0
Already on 'master'
Your branch is up-to-date with 'origin/master'.
...
```
Thanks for the help!

**Comment by jfly** [comment]
> I blindly did an update of all plugins, and now it's working, though I don't really understand why.

You can see in the output of the command you ran that previously you were using commit 375d161, which predates 8536995bdbd8e55b69fa807146926dfb81435bd4 (when we added the setup command).

> So all is good now!

Glad to hear it!
