### ISSUE TITLE
Provide `asdf direnv` utility.

### ISSUE THREAD

**Issue by vic** [asdf-community/asdf-direnv#27]
This way we can shorten the `asdf exec direnv *`, can provide an `asdf direnv allow`, and any other command we see convenient, and might even replace `bin/direnv_use_asdf`.

See [asdf extension commands](https://github.com/asdf-vm/asdf/blob/master/docs/plugins-create.md#asdf-extension-commands)

**Comment by michi-zuri** [comment]
I would prefer to find a way to be able to simply type `direnv allow`. For example by adding an 
`alias direnv="asdf exec direnv"` to the bash_profile or equivalent.

**Comment by vic** [comment]
working on this at #37

**Comment by deiga** [comment]
@vic Is this done or is something still missing?

**Comment by vic** [comment]
> @vic Is this done or is something still missing?

all done
