### ISSUE TITLE
asdf direnv rather slow and logging entire env for each asdf library

### ISSUE THREAD

**Issue by chadlwilson** [asdf-community/asdf-direnv#28]
I've been trying to switch to use `asdf-direnv` to get the great advantages noted here, as well as bind these two useful tools together and sort out environment variables linked to tool versions.

Unfortunately every time I switch into a folder with a `.envrc` it is extremely slow to load `asdf` via the `direnv` `use_asdf` directive and repeatedly logs out my entire shell environment for every asdf tool it is trying to load.

```
# 
# ...snipped...
#
PS1_SYMBOL_ENABLE=$'false';export COLORFGBG=$'7;0';export COMMAND_MODE=$'unix2003';export TERM_PROGRAM_VERSION=3.3.6;export ANDROID_SDK_ROOT=$'/Users/chad/Library/Android/sdk';export ANDROID_HOME=$'/Users/chad/Library/Android/sdk';export GPG_TTY=$'/dev/ttys003';export DOCKER_BUILDKIT=1;
direnv: using asdf java adopt-openjdk-11.0.5+10
direnv: using asdf nodejs 12.13.1
direnv: ([/Users/chad/.asdf/installs/direnv/2.20.0/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
# 
# ...snipped...
#
```

I can't work out why this is happening - is there something that I am missing that could be added as an FAQ? It's entirely possible there is an issue with my environment `PATH `or general shell configuration.

Using `zsh` with `oh-my-zsh`.

my `.zshrc` has this in the `oh-my-zsh` user configuration section (my `.profile` is just basic global env vars and shell aliases)
```
# User configuration
source ~/.profile
export PATH="$PATH:$HOME/.asdf/bin"
eval "$(asdf exec direnv hook zsh)"

# ...
```

**Environment:**
```
$ asdf --version
v0.7.5
$ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
$ cat ~/.direnvrc
source $(asdf which direnv_use_asdf)
$ cat .envrc
#!/usr/bin/env bash
use_asdf
$ cat ~/.tool-versions
ruby 2.5.3
python 3.7.2
nodejs 12.13.1
java system
maven system
direnv 2.20.0
$ cat .tool-versions
java adopt-openjdk-11.0.5+10
nodejs 12.13.1
helm 2.16.1
istioctl 1.3.5
docker-compose 1.25.0
```

**Comment by vic** [comment]
Try updating to latest master. Few days ago I added the ability to dump the
environment into cached envrc files. It would be created the first time
used or if .tool-versions changes. After that it's just matter of loading
those files without having to determine versions again. Also be sure to
read about exporting an empty log format for silencing direnv.

**Comment by imbsky** [comment]
This is little off-topic, but maybe we need to polish our documentation.

**Comment by vic** [comment]
Also, we need a `CHANGELOG`, will try to add one later.

**Comment by vic** [comment]
@chadlwilson also, after updating to master could you use, just to give us a little more info on your times? Also, please include the output of leaving and entering your directory again.

```
# your .envrc
time use asdf
```

I guess after the cache envrc file gets created, most time is spent checking if we can hit the cache or not. (see the usage at `bin/direnv_use_asdf` of function `_cksum`)

**Comment by chadlwilson** [comment]
Thanks @vic ! I had tried silencing direnv however this removed all the `direnv` prefixed messages but didn't remove the logs of my shell env.

I updated to `726c5a01af8edda72926155d8f06c411de7af209` (my bad; didn't occur to me that when adding the plugin with `asdf` that it might be outdated already) and the shell env dumps are going, but then I got

```
$ asdf exec direnv allow .envrc
direnv: loading .envrc
direnv: using asdf
/Users/chad/.asdf/plugins/direnv/bin/direnv_use_asdf: line 92: direnv: command not found
direnv: loading ~/.asdf/installs/direnv/2.20.0/env/2133843754-2263017340-4294967295-134636321
direnv: using asdf ruby 2.5.3
direnv: export +AWS_ACCESS_KEY_ID +AWS_DEFAULT_REGION +AWS_REGION +AWS_SECRET_ACCESS_KEY +AWS_SESSION_TOKEN ~PATH
```

I'm confused about this - isn't this a chicken-vs-egg thing? If `direnv` is only installed via asdf and not on the path, how can this script find it?

When I hack https://github.com/asdf-community/asdf-direnv/blob/master/bin/direnv_use_asdf#L92 and https://github.com/asdf-community/asdf-direnv/blob/master/bin/direnv_use_asdf#L187 to use `asdf exec direnv` calls like the other direnv calls in the script, the `command not found` errors go away.

I also had some weirdness with 
* needing to touch my `.envrc` because it was stopping after the first asdf tool (ruby in my case). Not really sure why that is.
* was seeing errors like `direnv: referenced /.envrc does not exist`. Re-allowing the `.envrc` seemed to make this one go away.

Anyway, with these changes it is lots faster and entirely usable now :-) After caching
```
direnv: loading .envrc
direnv: loading ~/.asdf/installs/direnv/2.20.0/env/2133843754-2263017340-2213930056-134636321
direnv: using asdf ruby 2.5.3
direnv: using asdf python 3.7.2
direnv: using asdf direnv 2.20.0
direnv: using asdf docker-compose 1.25.0
direnv: using asdf istioctl 1.3.5
direnv: using asdf helm 2.16.1
direnv: using asdf nodejs 12.13.1
direnv: using asdf java adopt-openjdk-11.0.5+10

real	0m0.936s
user	0m0.334s
sys	0m0.771s
direnv: export +AWS_ACCESS_KEY_ID +AWS_DEFAULT_REGION +AWS_REGION +AWS_SECRET_ACCESS_KEY +AWS_SESSION_TOKEN +NPM_CONFIG_PREFIX +RUBYLIB ~PATH
```

**Comment by michi-zuri** [comment]
Regarding the chicken and egg problem, I solved it for me by adding the asdf shims to end of PATH, this allows me to use globally enabled tools without this plugin and without the shims shadowing system tools. I can just type direnv allow instead asdf exec direnv allow. So it’s a hybrid solution that works best for me.

**Comment by michi-zuri** [comment]
The main problem of this issue seems to be fixed, with the cache it's not slow anymore. 

#33 got merged and fixes the error regarding direnv not being found. 

Can you confirm that you still encounter the problems you mentioned with the latest version?

> -    needing to touch my .envrc because it was stopping after the first asdf tool (ruby in my case). Not really sure why that is.
> -    was seeing errors like direnv: referenced /.envrc does not exist. Re-allowing the .envrc seemed to make this one go away.

If these issues still occur with the latest version, it would make sense to open a new issue and to investigate further under which circumstances they occur. My suggestion would be to close this issue now.

**Comment by chadlwilson** [comment]
Agreed, thanks for the assistance!
