### ISSUE TITLE
Add benchmark

### ISSUE THREAD

**Issue by imbsky** [asdf-community/asdf-direnv#3]

**Comment by imbsky** [comment]
without asdf-direnv:

| Command          |   Mean [ms] | Min [ms] | Max [ms] | Relative |
| :--------------- | ----------: | -------: | -------: | -------: |
| `node --version` | 189.7 ± 2.7 |    185.6 |    194.0 |     1.00 |

with asdf-direnv:

| Command          | Mean [ms] | Min [ms] | Max [ms] | Relative |
| :--------------- | --------: | -------: | -------: | -------: |
| `node --version` | 4.3 ± 0.4 |      3.6 |      6.0 |     1.00 |

**Comment by imbsky** [comment]
without asdf-direnv:

| Command           |    Mean [ms] | Min [ms] | Max [ms] | Relative |
| :---------------- | -----------: | -------: | -------: | -------: |
| `rustc --version` | 195.2 ± 84.7 |    163.2 |    436.2 |     1.00 |

with asdf-direnv:

| Command           | Mean [ms] | Min [ms] | Max [ms] | Relative |
| :---------------- | --------: | -------: | -------: | -------: |
| `rustc --version` | 5.3 ± 0.5 |      4.2 |      7.2 |     1.00 |

**Comment by vic** [comment]
Nice, how about `npm install -g`, see related issue: 

https://github.com/asdf-vm/asdf-nodejs/issues/46#issuecomment-445561567

**Comment by imbsky** [comment]
without asdf-direnv:

| Command               |    Mean [ms] | Min [ms] | Max [ms] | Relative |
| :-------------------- | -----------: | -------: | -------: | -------: |
| `npm install -g yarn` | 870.0 ± 12.9 |    848.4 |    894.6 |     1.00 |

with asdf-direnv:

| Command               |    Mean [ms] | Min [ms] | Max [ms] | Relative |
| :-------------------- | -----------: | -------: | -------: | -------: |
| `npm install -g yarn` | 683.3 ± 17.3 |    667.9 |    725.1 |     1.00 |

**Comment by imbsky** [comment]
I think that is not an issue with asdf.
https://github.com/Polymer/tools/issues/2583
