### ISSUE TITLE
`asdf shell` doesn't work

### ISSUE THREAD

**Issue by deiga** [asdf-community/asdf-direnv#30]
Since we don't source the `asdf` script anymore we don't get `asdf shell` -command and I can't figure out if there is a way to duplicate the functionality with direnv

**Comment by vic** [comment]
Oh yes, I moved the `asdf` function outside of `$ASDF_DIR/asdf.sh`, now it's at $ASDF_DIR/lib/asdf.sh`, we just have to source it somewhere.

**Comment by michi-zuri** [comment]
@vic How do you mean you moved it to $ASDF_DIR/lib/asdf.sh? I don't see anything other than `utils.sh` and `commands/` in that folder. Also isn't this outside of the plugin?

**Comment by vic** [comment]
@michi-zuri You have to update your asdf to latest master.

**Comment by vic** [comment]
@deiga working on this at #37
