### ISSUE TITLE
direnv_use_asdf: line 92: direnv: command not found`

### ISSUE THREAD

**Issue by omares** [asdf-community/asdf-direnv#32]
Hey,

I have a `.envrc` inside my home directory, as I want the globally installed plugins to be loaded by default.

When executing `which node` i get the error `/Users/omares/.asdf/plugins/direnv/bin/direnv_use_asdf: line 92: direnv: command not found`. The full output can be seen below.

My system does not have `direnv` globally installed and it seems this plugin only provides direnv via the `asdf exec direnv...` call. [Shouldn't the affected code line reflect this](https://github.com/asdf-community/asdf-direnv/blob/master/bin/direnv_use_asdf#L92)? Or did is miss something when installing the direnv plugin?

```
asdf current
direnv         2.20.0   (set by /Users/omares/.tool-versions)
java           adopt-openjdk-11.0.5+10 (set by /Users/omares/.tool-versions)
maven          3.6.3    (set by /Users/omares/.tool-versions)
nodejs         10.17.0  (set by /Users/omares/.tool-versions)
python         3.8.0    (set by /Users/omares/.tool-versions)
ruby           2.6.5    (set by /Users/omares/.tool-versions)
```

```
which node
/usr/local/bin/node
direnv: loading .envrc
direnv: using asdf
/Users/omares/.asdf/plugins/direnv/bin/direnv_use_asdf: line 92: direnv: command not found
direnv: loading ~/.asdf/installs/direnv/2.20.0/env/1337337645-3443856708-4294967295-1908856927
direnv: using asdf direnv 2.20.0
```

**Comment by omares** [comment]
fyi, installing direnv via `brew install direnv` fixed the issue. Not sure if this step is intended/required or not?

**Comment by michi-zuri** [comment]
> fyi, installing direnv via `brew install direnv` fixed the issue. 

Homebrew should not be needed at all to install direnv with the asdf direnv plugin. The problem lies elsewhere.

**Comment by michi-zuri** [comment]
Do you mean that when you open a new terminal window nothing happens until you type in the command `which node` and this produces the following output? 

> ```
> which node
> /usr/local/bin/node
> direnv: loading .envrc
> direnv: using asdf
> /Users/omares/.asdf/plugins/direnv/bin/direnv_use_asdf: line 92: direnv: command not found
> direnv: loading ~/.asdf/installs/direnv/2.20.0/env/1337337645-3443856708-4294967295-1908856927
> direnv: using asdf direnv 2.20.0
> ```

That would be weird. The second line suggests that the homebrew version of node is in your PATH before asdf installed node. 
I don't get how the which command would trigger the loading of .envrc 
Can you be more precise about the single steps you took to get  the quoted output? Also the content of your ~/.bash_profile would be helpful for debugging.

**Comment by omares** [comment]
> Do you mean that when you open a new terminal window nothing happens until you type in the command which node and this produces the following output?

Yes.

> That would be weird. The second line suggests that the homebrew version of node is in your PATH before asdf installed node.

This is my $PATH value before taking any action on the console. Notice the `/usr/local/bin` entry, this is where homebrew installs its binaries. And yes i have `node` also installed via homebrew, as it was a dependency of another package.

```
/Users/omares/.zplugin/snippets/sdkman:/usr/local/opt/asdf/bin:/Users/omares/.zplugin/plugins/junegunn---fzf-bin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/Users/omares/.zplugin/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbi
```

After direnv doing its magic $PATH looks as follows. The asdf paths come first

```
/Users/omares/.asdf/installs/java/adopt-openjdk-11.0.5+10/bin:/Users/omares/.asdf/installs/nodejs/10.17.0/bin:/Users/omares/.asdf/installs/nodejs/10.17.0/.npm/bin:/Users/omares/.asdf/installs/ruby/2.6.5/bin:/Users/omares/.asdf/installs/maven/3.6.3/bin:/Users/omares/.asdf/installs/python/3.8.0/bin:/Users/omares/.asdf/plugins/direnv/shims:/Users/omares/.asdf/installs/direnv/2.20.0/bin:/Users/omares/.zplugin/snippets/sdkman:/usr/local/opt/asdf/bin:/Users/omares/.zplugin/plugins/junegunn---fzf-bin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/Users/omares/.zplugin/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

> Can you be more precise about the single steps you took to get the quoted output?

Opening a new terminal and entering `which node`, thats all.

> Also the content of your ~/.bash_profile would be helpful for debugging.

I am using zsh with zplugin, for convenience I have the asdf related code in a separate script that is being sourced:

```
export PATH="/usr/local/opt/asdf/bin:$PATH"

eval "$(asdf exec direnv hook zsh)"
```

**Comment by omares** [comment]
To make sure i moved the contents of my separate script to the `.zshrc` file. This fixes the issue of the trigger problem. Meaning that i see the error directly when opening a new terminal. Still, i see the error about direnv not being found.

**Comment by michi-zuri** [comment]
Ok, I think what that line does is checking if the environment needs to recreated or can be used from cache. Adding asdf exec would probably fix this, could you try this locally ? 

The reason why asdf exec is needed is that the asdf shims directory is not in PATH, addi ng the shims directory to PATH would allow you use the direnv command as specified in your .tool-versions file, before direnv loads it into PATH specifically, but has the potential to cause other problems.

**Comment by omares** [comment]
This is how line 92 now looks like

```
cksum <(pwd) <(echo "$@") <(asdf exec direnv status) <(ls -l "$file") | cut -d' ' -f 1 | tr $'\n' '-' | sed -e 's/-$//'
```

Also had to change line 187 

```
asdf exec direnv dump bash | sed -e $'s#;export#\\\nexport#g' | sed -e 's#;$##'
```

Now the error is gone but it seems direnv is not doing its magic anymore, aka not loading the asdf plugins :(

(on opening the terminal i see this output)
```
direnv: loading .envrc
direnv: using asdf
direnv: loading ~/.asdf/installs/direnv/2.20.0/env/1337337645-3443856708-446675707-2130993034
direnv: using asdf direnv 2.20.0
direnv: export +TESTING_OTA

❯ node --version
v13.2.0

❯ echo $PATH
/Users/omares/.zplugin/snippets/sdkman:/Users/omares/.zplugin/plugins/junegunn---fzf-bin:/usr/local/opt/asdf/bin:/usr/local/opt/findutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/Users/omares/.zplugin/polaris/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by michi-zuri** [comment]
What does your .envrc file look like? 
Could try changing it to

```
use asdf local
```

Then typing `asdf exec direnv allow`

**Comment by omares** [comment]
Ok, had to regenerate the cached env file generated by `asdf-direnv`, not everything works. Sorry about that!

Shall i create a PR that applies the changes?

**Comment by michi-zuri** [comment]
Would be great!

**Comment by omares** [comment]
Btw is it the correct approach to create a `.envrc` in my home directory to force loading the global plugins?

**Comment by michi-zuri** [comment]
The way I understand is that if you create a local .envrc  somewhere in a project it would override any higher up in the directory tree. 
`use asdf` in a .envrc of a project would include all tools that show up when you type asdf current regardless of any other .envrc anywhere on your system.

**Comment by omares** [comment]
The scenario you describe is correct when moving into a project directory.

What if I would like to use node/python/etc directly from my console, inside my home dir (without cding into a project dir)? What is the recommended way to enforce loading of the globally defined asdf plugins?

Also shouldn't asdf-direnv add itself to $PATH? Making direnv globally available?

**Comment by michi-zuri** [comment]
> What if I would like to use node/python/etc directly from my console, inside my home dir (without cding into a project dir)? Is there a recommended way to enforce loading of the globally defined asdf plugins?
> 
> Also shouldn't asdf-direnv add itself to $PATH? Making direnv globally available?

Let's discuss this in a new issue.
