### ISSUE TITLE
asdf is defined as a function, so dirname cannot be applied after command -v

### ISSUE THREAD

**Issue by michi-zuri** [asdf-community/asdf-direnv#38]
~~This doesn't work after `lib/asdf.sh` is sourced.~~
https://github.com/asdf-community/asdf-direnv/blob/7b750247694e37ea8bb555ab5100b450c2b7b32e/bin/command#L28

asdf is an executable in `.asdf/bin/`, but also defined as a function in `.asdf/lib/asdf.sh`, therefore `command -v asdf` returns just `asdf` whereas `which asdf` returns `~/.asdf/bin/asdf`. 

I don't think it would be wrong in this case to rely on `which`, even though it is recommended against in most cases. 
EDIT: Regardless of the above observations, it doesn't seem to cause any issues.

**Comment by michi-zuri** [comment]
strangely though I can't make the error go away that pops up when starting a terminal `usage: dirname path` by changing `command -v` to `which`, neither by commenting out the line where I source `.asdf/lib/asdf.sh`, the only thing that makes it go away is disabling asdf direnv hook in .bash_profile or activating an environment with .envrc...

**Comment by michi-zuri** [comment]
`usage: dirname path` is triggered by running `asdf direnv` but not when running `eval $(asdf which direnv)` or `asdf exec direnv`, so that's why the error persisted. When I replaced  
```
eval "$(asdf direnv hook bash)"
```
with 
```
eval "$(asdf exec direnv hook bash)"
```
in my bashrc the error disappeared.
Changing `command -v` to `which` in the mentioned line above actually had no effect, so please ignore my first post.

**Comment by deiga** [comment]
This seems to be fixed now, can you confirm?

**Comment by michi-zuri** [comment]
The Readme instructions have adopted the suggested fix, so yes this issue can be closed :)
