### ISSUE TITLE
Getting `unbound variable` error when loading ~/.envrc 

### ISSUE THREAD

**Issue by comfortablynick** [asdf-community/asdf-direnv#43]
I've tried following the instructions and have also uninstalled/reinstalled direnv through asdf. Am I doing something wrong? I assume I am since I haven't seen this error reported. Any ideas?

```sh
direnv: loading ~/.envrc                                                                                                                                                                             
direnv: using asdf
direnv: Creating env file /home/nick/.asdf/installs/direnv/2.21.1/env/89915010-3101997489-2605339247-3694453858
/home/nick/.asdf/lib/utils.sh:116: $1: unbound variable
find: ‘’: No such file or directory
direnv: referenced  does not exist
direnv: error exit status 1
```

I am trying to use the `.envrc` at the root of my home drive to handle my global asdf installs.

#### `~/.envrc`

```sh
source "$(asdf which direnv_use_asdf)"
use asdf
```

#### `~/.tool-versions`
```
python 3.7.4
nodejs 10.16.3
luaJIT 2.0.1--2.4.4
direnv 2.21.1
```

#### `.zshrc`
```sh
eval "$(asdf exec direnv hook zsh)"
```

**Comment by michi-zuri** [comment]
I think this could be fixed by the upcoming release of the follow-up version. Could give that a try.

**Comment by comfortablynick** [comment]
Is this happening to everyone, or is there some specific condition that causes it? I'd love to get this working but right now it doesn't seem to help me use my asdf tools without shims.

**Comment by michi-zuri** [comment]
I will try to reproduce the setup and see if I get the same error, then get back to you.

**Comment by michi-zuri** [comment]
Hi there, 
I can confirm the bug with direnv version 2.21.1
I can also tell you the the bug does not occur with direnv version 2.20.0
So the simple solution for you would be to run 
```
rm .envrc

asdf install direnv 2.20.0

asdf global direnv 2.20.0

echo -e "# File: ~/.config/direnv/direnvrc \n\
source $(asdf which direnv_use_asdf)\n\
# Uncomment the following line to make direnv silent by default.\n\
# export DIRENV_LOG_FORMAT=\"\"" \
> ~/.config/direnv/direnvrc

echo 'use asdf' > .envrc && asdf exec direnv allow .envrc 
```

Hope this helps.

**Comment by michi-zuri** [comment]
As a follow-up: 
I can confirm that direnv version 2.21.2 does not suffer from this problem, neither in bash, nor in zsh, so if you need the newest direnv, try that version instead of 2.20.0.

**Comment by comfortablynick** [comment]
Thanks! 2.21.2 seems to have done the trick and is working as expected.
