### ISSUE TITLE
misses the mark

### ISSUE THREAD

**Issue by ethanj** [asdf-community/asdf-direnv#45]
Just some feedback...

I was excited to find this repo, but decided not to use it.
The promise of direnv managed environment vars sped up with caching seemed like a no-brainer.
The issue is the pita and cognitive load added to running normal asdf managed commands where you have to type asdf exec for "normal" command usage. The whole point of asdf and direnv are to set it and forget it invisibly manage versions. 
This is a deal-breaker.

**Comment by vic** [comment]
Once you have followed the instructions in the README, you dont have to `asdf exec ..` for "normal" command usage. You just type your commands since they are placed in PATH by direnv. 

This is an invalid issue, closing now.

**Comment by michi-zuri** [comment]
The only case where I needed to prepend asdf exec was with "direnv allow". A simple alias direnv='asdf exec direnv' does the trick.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ethanj** [comment]
OK gave it another shot...

  % more ~/.config/direnv/direnvrc
source $(asdf which direnv_use_asdf)

  % more .envrc
use asdf
  
  % asdf plugin-add direnv
  Cloning into '/Users/ethan/.asdf/plugins/direnv'...
  remote: Enumerating objects: 23, done.
  remote: Counting objects: 100% (23/23), done.
  remote: Compressing objects: 100% (20/20), done.
  remote: Total 328 (delta 7), reused 5 (delta 0), pack-reused 305
  Receiving objects: 100% (328/328), 77.68 KiB | 2.22 MiB/s, done.
  Resolving deltas: 100% (163/163), done.
  % asdf install direnv 2.20.0
  ∗ Downloading and installing direnv...
  The installation was successful!
  % asdf global  direnv 2.20.0
new terminal...

direnv: loading .envrc
direnv: using asdf
direnv: Creating env file /Users/ethan/.asdf/installs/direnv/2.20.0/env/927841655-2557873669-1747158408-2473097242
/Users/ethan/.asdf/plugins/direnv/bin/direnv_use_asdf: line 158: find_versions: command not found
direnv: referenced /.envrc does not exist
  
--- 

seems there is an error, which i assume is preventing correct path resolution:

% which node
/usr/local/bin/node
% node --version
v12.8.0
% asdf which node
/Users/ethan/.asdf/installs/nodejs/13.0.1/bin/node
% asdf exec node --version
v13.0.1

**Comment by ethanj** [comment]
for future reference.. fixed this issue with
`asdf update`

so now everything is good to go
sorry for the initial false alarm, but maybe you should add to the readme to make sure to asdf update.
