### ISSUE TITLE
[source (asdf which direnv_use_asdf)] doesn't work in fish shell

### ISSUE THREAD

**Issue by dfdgsdfg** [asdf-community/asdf-direnv#46]
### Environments
- MacOs
- FishShell

`source (asdf which direnv_use_asdf)` is equivalent to `source $(asdf which direnv_use_asdf)` in bash

```bash
$ source (asdf which direnv_use_asdf)

~/.asdf/plugins/direnv/shims/direnv_use_asdf (line 25): Command substitutions not allowed
use_asdf() {
        ^
from sourcing file ~/.asdf/plugins/direnv/shims/direnv_use_asdf
source: Error while reading file '/Users/user/.asdf/plugins/direnv/shims/direnv_use_asdf'
```

**Comment by vic** [comment]
I guess you are trying to source that on the wrong place (perhaps on your interactive fish shell)

As noted on README, that line should be included in either `~/.config/direnv/direnvrc` or a `.envrc`, and both of them will be loaded as bash scripts by `direnv`.

**Comment by dfdgsdfg** [comment]
@vic 
I just mis understood document. I changed `direnvrc`'s command to fish shell style.

Everything is just perfect. Thanks.
