### ISSUE TITLE
No error reported if selected version is not already installed.

### ISSUE THREAD

**Issue by vic** [asdf-community/asdf-direnv#49]
For example, `asdf list rust` yields only `1.39.0` but if you set the following on `.tool-versions`: 

```
rust 1.41.1
```

No error is reported. We should somehow print a message that the version is not already installed.

`PATH` includes `$HOME/.asdf/installs/rust/1.41.1/bin` but that doesn't even exist.

**Comment by deiga** [comment]
Is this a bug with `asdf-direnv`? Doesn't this functionality originate from https://github.com/asdf-vm/asdf
