### ISSUE TITLE
Direnv performance improvement on shell startup time

### ISSUE THREAD

**Issue by dagadbm** [asdf-community/asdf-direnv#57]
Currently, using asdf-direnv and setting up a gloval .envrc file makes the shell unusably slow.

To combat this I did the following on my setup:

on my zshrc i just setup asdf regularly, and include the direnv hook which looks like this:

```
# asdf
. $HOME/.asdf/asdf.sh
fpath=(${ASDF_DIR}/completions $fpath)
autoload -Uz compinit
compinit
## asdf direnv setup
eval "$(asdf exec direnv hook zsh)"
```

afterwards i do create a global direnv file with the following contents, which are basically copy pasted from .asdf/asdf.sh

```
source $(asdf which direnv_use_asdf)

# Uncomment the following line to make direnv silent by default.
# export DIRENV_LOG_FORMAT=""

## Unset asdf shims to use asdf direnv properly
ASDF_BIN="$HOME/.asdf/bin"
ASDF_USER_SHIMS="$HOME/.asdf/shims"
[[ ":$PATH:" == *":${ASDF_BIN}:"* ]] && PATH="${PATH//$ASDF_BIN:/}"
[[ ":$PATH:" == *":${ASDF_USER_SHIMS}:"* ]] && PATH="${PATH//$ASDF_USER_SHIMS:/}"
export PATH="${ASDF_BIN}:$PATH"
```

What does this give me?

Basically I get all the benefits of using asdf globally with no cons regarding shell startup time by using asdf-direnv.

If for some reason I do indeed need some custom direnv solution which doesnt use my global asdf settings then ofc we go into direnv land.

This makes the shell startup time a little bit more bearable if you have a lot of asdf plugins installed.

If someone ends up on the same situation as me, this is how i solved it.

Aso, I do know you can use some direnv caching using nix, but I had never heard of nix before and I do not want to learn yet another new thing to do this so voila.

**Comment by michi-zuri** [comment]
A hybrid like you describe is a reasonable solution indeed if you need very zippy startup times. This may deserve an honorable mention in the readme.

**Comment by vic** [comment]
Yes, please consider improving our documentation.

**Comment by dagadbm** [comment]
I have just updated your plugin and this following setup works fine for me:

```
.zshrc
# asdf must be sourced before compinit
. $HOME/.asdf/asdf.sh
fpath=(${ASDF_DIR}/completions $fpath)
# Hook direnv into your shell.
eval "$(asdf exec direnv hook zsh)"
export DIRENV_LOG_FORMAT=
# ... afterwards i am sourcing oh my zsh (i know its nooby but i  dont know prezto or zinit)
# source $ZSH/oh-my-zsh.sh
```

on the direnvrc i only have this
```
source "$(asdf direnv hook asdf)"

# Fetch the nvim python provider if needed
use_nvim_python_provider() {
	pip show pynvim &> /dev/null || pip install pynvim &> /dev/null
}

# basic usage {{{

# .envrc
# use asdf
# layout python python3

# .tool-versions
# python 3.8.1
# nodejs 10.21.0
# }}}
```

**Comment by dagadbm** [comment]
but i also am using powerlevel10k prompt shell which might have probably fixed the start up time i had with the shell...

**Comment by smorimoto** [comment]
Is this already solved?
