### ISSUE TITLE
Should direnv_use_asdf be part of this repo or direnv ?

### ISSUE THREAD

**Issue by vic** [asdf-community/asdf-direnv#6]
I did a PR for direnv https://github.com/direnv/direnv/pull/534 that is basically the content of `shims/direnv_use_asdf`. The idea of the PR is for `use_asdf` to be part of direnv stdlib (as many other `use_*` it has)

However, I'm now wondering if that's something we really want.

1) If `use asdf` were part of direnv's stdlib, asdf users would not need to add

```
source $(asdf which direnv_use_asdf) # provided by asdf-direnv
use asdf
``` 

but just `use asdf`

2) The advantage of keeping it on this repo, is that we might be able to change it faster and users would just `asdf plugin-update direnv` instead of waiting for the next direnv release.

What do you think, @imbsky ?
Shall I just close the PR and keep the script here ?

**Comment by imbsky** [comment]
To be honest, I don't think many asdf users will use this plugin. It should be used by some core users. In that case, we should respect responsiveness to changes. So I like option 2.
