### ISSUE TITLE
Support 64-bit ARM Architecture for Linux

### ISSUE THREAD

**Issue by jwillikers** [asdf-community/asdf-direnv#61]
Would it be possible to support 64-bit ARM / Linux? I would like to use this plugin on my Pinebook Pro. I can create an upstream request with direnv to provide 64-bit ARM binaries for Linux if that is necessary. Thanks!

**Comment by smorimoto** [comment]
Yes, they currently only have this for release artifacts, so I recommend asking upstream.

```
direnv.linux-arm: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go
```

**Comment by smorimoto** [comment]
@jwillikers If you are not interested in managing the version of direnv, you can also use direnv installed by your system package manager by specifying "system" as the version.

**Comment by jwillikers** [comment]
@smorimoto I've opened issue direnv/direnv#724 upstream to release 64-bit ARM binaries for Linux.

Using the "system" keyword as a version for direnv doesn't seem to work correctly. I can install direnv from the AUR and specify "system" as the global version, but then asdf can't find it.

```sh
$ asdf which direnv
unknown command: direnv. Perhaps you have to reshim?
```

**Comment by smorimoto** [comment]
Hmm... Any idea? @vic

**Comment by smorimoto** [comment]
@jwillikers The last commit fixed this issue. The problem with "system" is a different issue, so I close this issue.

**Comment by jwillikers** [comment]
@smorimoto Thanks!
