### ISSUE TITLE
`use_asdf` command not found

### ISSUE THREAD

**Issue by farzadmf** [asdf-community/asdf-direnv#64]
Hi, I just became familiar with `asdf` and I'm trying to use it. I've installed this plugin, `direnv`, and set the global and I have created the `~/.envrc` with this content:
```
use asdf
```

However, when I run `direnv allow`, I see the following error message:
```
direnv: loading ~/.envrc
direnv: using asdf
environment:961: use_asdf: command not found
```

Sorry if this is a stupid question, but is there something I'm missing?

**Comment by farzadmf** [comment]
Sorry, my bad, I didn't notice the documentation part saying the following line makes `use asdf` available:
```bash
source "$(asdf direnv hook asdf)"
```

**Comment by dlo** [comment]
The command above is incorrect. It should be `eval "$(asdf direnv hook bash)"`, where `bash` can be replaced by your shell.
