### ISSUE TITLE
Still have to asdf reshim python 

### ISSUE THREAD

**Issue by cocoonkid** [asdf-community/asdf-direnv#72]
Still have to asdf reshim python .

I followed the setup  to the point but I can't  get it to work.

asdf works perfectly but when installing something with pip it does not find it in its path until i reshim.

asdf-direnv is setup correctly I think,

Which information could I provide to make triage  of this issue successful?

**Comment by missingcharacter** [comment]
should be easy to confirm, just run

```shell
env | grep PATH | grep "$(asdf where python)/bin"
```

**Comment by cocoonkid** [comment]
Wow. Thanks for the swift reply. I confirmed the same issue with npm.  
I use arch linux btw (and macos by the side)

```
env | grep PATH | grep "$(asdf where python)/bin"
```
does not produce a  result.

**Comment by cocoonkid** [comment]
I have in my zshrc:

```
# enable direnv 
eval "$(direnv hook zsh)"

# A shortcut for asdf managed direnv.
direnv() { asdf exec direnv "$@"; }
```

**Comment by missingcharacter** [comment]
do you have `.envrc` in your project or maybe on your `${HOME}/.envrc`?

**Comment by cocoonkid** [comment]
I was about to ask now if I need a .envrc for the globals ?  I was under the impression this is needed only for local specific projects ?

**Comment by missingcharacter** [comment]
we're all n00bs

**Comment by cocoonkid** [comment]
okay 

```
On your project directory, create an .envrc file like this:

# File:${HOME}/.envrc
use asdf
```

Finally, run direnv allow to trust your new file.

**Comment by missingcharacter** [comment]
would you mind making a PR with this suggestion?

**Comment by cocoonkid** [comment]
my first PR?

I'm scared shitless.

**Comment by cocoonkid** [comment]
alright :+1:   put on my list. incoming within this week.

**Comment by airtonix** [comment]
@cocoonkid so you're saying that we need to make a file in the projects directory that has exactly these contents: 

```
On your project directory, create an .envrc file like this:

# File:${HOME}/.envrc
use asdf


Finally, run direnv allow to trust your new file.
```

surely you mean 

```
# File:${HOME}/.envrc
use asdf
```

 ?????
