### ISSUE TITLE
Issues setting up with fish

### ISSUE THREAD

**Issue by mfilej** [asdf-community/asdf-direnv#74]
Hello, I'm having some issues getting asdf-direnv working with fish.

I have installed the plugin, then installed direnv 2.28.0 through the plugin and activated it globally.

I have added this to my `config.fish`:
```fish
asdf direnv hook fish | source
```

And this to my `.config/direnv/direnvrc`:
```
eval "$(asdf exec direnv hook bash)"  
```

And then I have added `use asdf` to my project's .envrc.

When cd-ing into the project, I see this:
```
direnv: loading ~/[…]/.envrc
direnv: using asdf
/bin/bash:960: use_asdf: command not found
```

The output for `asdf exec direnv hook bash` is the following:
```
_direnv_hook() {
  local previous_exit_status=$?;
  trap -- '' SIGINT;
  eval "$("/Users/miha/.asdf/installs/direnv/2.28.0/bin/direnv" export bash)";
  trap - SIGINT;
  return $previous_exit_status;
};
if ! [[ "${PROMPT_COMMAND:-}" =~ _direnv_hook ]]; then
  PROMPT_COMMAND="_direnv_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
fi
```

But if I try to run `"/Users/miha/.asdf/installs/direnv/2.28.0/bin/direnv" export bash` manually, there is no output at all.

I'm not sure I understand where the `use_asdf()` function is supposed to come from?

**Comment by smorimoto** [comment]
What is the current your asdf version.

**Comment by mfilej** [comment]
Just installed through homebrew:
```
$ asdf version
v0.8.0
```

**Comment by smorimoto** [comment]
The contents of file `~/.config/direnv/direnvrc` must be:

```
source "$(asdf direnv hook asdf)"
```

**Comment by smorimoto** [comment]
See https://github.com/asdf-community/asdf-direnv#global-asdf-direnv-integration

**Comment by mfilej** [comment]
> The contents of file `~/.config/direnv/direnvrc` must be:
> 
> ```
> source "$(asdf direnv hook asdf)"
> ```

When I try this I still get `command not found`:
```
$ touch .envrc
/Users/miha/.asdf/plugins/direnv/lib/commands/command-hook-asdf.bash
direnv: loading ~/[…]/.envrc
direnv: using asdf
/bin/bash:960: use_asdf: command not found
```

And if I try to simply run `asdf direnv hook asdf` in my shell I see no output (exit status is 0).

**Comment by mfilej** [comment]
I have attempted setting this up on fish on a new machine and I have gotten slightly further.

I tried to simplify everything down as much as possible:

```
$ cd example
direnv: loading ~/example/.envrc
direnv: using asdf
/Users/miha/.asdf/plugins/direnv/lib/commands/command.bash:20: /opt/homebrew/lib/utils.bash: No such file or directory
direnv: referenced  does not exist

$ cat .envrc
use asdf
```

Any ideas?

**Comment by kjaleshire** [comment]
Apparently Homebrew now installs `asdf` into the `libexec` directory that may need to be accounted for. See details in the formula commit:

https://github.com/Homebrew/homebrew-core/commit/cd3d21ba3a2c1041b64191b82cee3bffcbe2efdf#diff-298ebac561811ce26c00772e4542290af157aebc91a0e05fb9270ea3e5fbbb2e

I may be able to submit a patch later.

**Comment by kjaleshire** [comment]
The underlying issue of the incorrect `$ASDF_DIR` variable was rectified. This is working again.

https://github.com/Homebrew/homebrew-core/commit/cd3d21ba3a2c1041b64191b82cee3bffcbe2efdf#r62305881

**Comment by mfilej** [comment]
Seems to work beautifully, thank you!
