### ISSUE TITLE
Global `use asdf` 

### ISSUE THREAD

**Issue by Matts966** [asdf-community/asdf-direnv#77]
Thank you for this great plugin :bow:

I see in [this commit](https://github.com/asdf-community/asdf-direnv/commit/1f8edbc4de23995f5b5f04f99a34903b93b8b820#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R115), we could set `use asdf` globally using `direnvrc` before.

However, currently setting `use asdf` on `direnvrc` does not work and my env is not loaded without `.envrc`.

Is it still possible to set `use asdf` globally in `direnvrc` ?

**Comment by vic** [comment]
I believe for direnv to work it needs a `.envrc` file to exist in any directory you might want to change the environment. the `direnvrc` file you mention is quite different: its used to load auxiliary functions you might always need on all your `.envrc` files.

**Comment by Matts966** [comment]
@vic 
Thank you for your explanation!
I understood this should be a feature request for direnv, though it is not intended behavior for now.
