### ISSUE TITLE
README: environment variables need to be exported

### ISSUE THREAD

**Issue by glasserc** [asdf-community/asdf-direnv#79]
Thanks for this plugin! I've found it very useful.

I recently tried to use a version of a new tool on a work project. Because it's a work project, I didn't want to touch `.tool-versions` just for my own experimentation. I saw the instructions in the `Pro-tips` section of the documentation, which says:

```
*    You can override any tool version via environment variables.

      See the asdf documentation regarding versions from environment variables.

# .envrc
ASDF_PLUGIN_VERSION=1.0
use asdf
```

I tried this and it didn't work. I had to `export` the environment variable for it to work. (I also typoed `asdf` as `adsf`, but that's not something I can file an issue about.) Is this expected? If so, I'd like to request that we put `export` in the example to make things easier for the next person.

I'm using Ubuntu, fish, direnv 2.21.3 (from distribution), asdf-direnv `master`.

**Comment by RCristiano** [comment]
I believe this happens because the fish syntax for setting a variable is different
Try:
```fish
# .envrc
set -l ASDF_PLUGIN_VERSION 1.0
use asdf
```
It should work, but I haven't tested it, sorry
The documentation was written for bash

**Comment by smorimoto** [comment]
What you need here is `export`. Even if you are using fish, you have to use shell syntax in `.envrc`.
