### ISSUE TITLE
How to make `use asdf` available for Fish and Bash?

### ISSUE THREAD

**Issue by penyuan** [asdf-community/asdf-direnv#85]
I've followed the instructions in the README to set up `asdf` and `asdf-direnv` on my system and so far it works except one step.

The current README for asdf-direnv tells me I should add the following to my `~/.config/direnv/direnvrc` to enable `use asdf`: 

`source "$(asdf direnv hook asdf)"`

This line works for Bash but not Fish which doesn't do `$`-style command substitutions. **How should I set up my `~/.config/direnv/direnvrc` so that it works for both Bash and Fish shells?**

By the way, I tried running just `asdf direnv hook asdf` in my Fish shell but it didn't give any visible output. Is this normal?

**Comment by smorimoto** [comment]
I don't know exactly what you want, but if you want this to work with fish, it's enough to do something like:

- `/Users/smorimoto/.config/fish/config.fish`

```fish
# direnv
asdf exec direnv hook fish | source
set -gx DIRENV_LOG_FORMAT
```

- `/Users/smorimoto/.config/direnv/direnvrc`

```
source "$(asdf direnv hook asdf)"
```

- `/Users/smorimoto/.envrc`

```
use asdf
```
