### ISSUE TITLE
"system" versions no longer working

### ISSUE THREAD

**Issue by amrox** [asdf-community/asdf-direnv#90]
Since https://github.com/asdf-community/asdf-direnv/pull/88 "system" entries in `.tool-versions` are not working.

**Environment**
OS `ubuntu 18.04`
asdf version `v0.9.0-9ee24a3`
asdf-direnv version `d3f53b4bc9d8f810e7abc5cefcb30d97933af31f` (`master` at time of writing)

**Steps to reproduce**

1. Create a `.tool-versions` file with a tool that has "system" for a version. Any tool will work. I used `shftmt`.
```
# .tool-versions
shfmt system
```
2. Ensure `asdf-direnv` is set up properly.
3. Reload the environment, via `cd` or `direnv reload`

**Expected**

Behavior as of `c4df7c1f71c3183cfab662beee656a8e4e3b5594` (commit before merge of https://github.com/asdf-community/asdf-direnv/pull/88)

```
❯ direnv reload
direnv: using asdf
direnv: Creating env file /home/amrox/.asdf/installs/direnv/2.30.1/env/2166439333-3797687844-3530659221-164655541
direnv: loading ~/.asdf/installs/direnv/2.30.1/env/2166439333-3797687844-3530659221-164655541
direnv: using asdf direnv 2.30.1
direnv: using asdf shfmt system
direnv: loading ~/tmp/asdf-direnv-bug/.envrc
direnv: export ~PATH
```

**Actual**

```
❯ direnv reload
direnv: using asdf
direnv: Creating env file /home/amrox/.asdf/installs/direnv/2.30.1/env/2166439333-3797687844-1136522493-164655541
direnv: shfmt system not installed. Run 'asdf install' and try again.
direnv: Error generating asdf cached envrc
```

I create have "system" entries for many tools in my `$HOME/.tool-versions` so things like `asdf exec` always work.

Any help would be greatly appreciated. This plugin has been a game-changer for me!

**Comment by jfly** [comment]
Eep, I'm not surprised I broke this, I didn't even know you could *do* something like this!

I'll see what I can do to fix this.
