### ISSUE TITLE
bash use_asdf command not found for zsh

### ISSUE THREAD

**Issue by udl** [asdf-community/asdf-direnv#94]
Hi and thank you for the great tool!
I'm trying to make it work on OSX with default shell ZSH and oh-my-zsh installed.
I installed direnv via 
```
asdf plugin-add direnv
asdf install direnv latest
asdf global direnv latest
```

My `~/.zshrc` has the line `eval "$(direnv hook zsh)"` after loading asdf.
My projects `/my/project/.envrc` looks like this:
```
export SOMETHING=something
use asdf
```

After restarting my terminal when I enter the project directory, I see the following output:
```
direnv: loading ~/my/project/.envrc
direnv: using asdf
/bin/bash:987: use_asdf: command not found
direnv: export +SOMETHING
```

The export works just fine. But I'm puzzled why it tries to use asdf for bash, when my shell is zsh.
Did I miss anything?

Thank you!

**Comment by jfly** [comment]
@udl did you create/update a `~/.config/direnv/direnvrc` when installing asdf-direnv as [per these instructions](https://github.com/asdf-community/asdf-direnv#global-asdf-direnv-integration)? That's what provides the `use_asdf` command you appear to be missing.

> But I'm puzzled why it tries to use asdf for bash, when my shell is zsh.

direnv *always* evaluates the `.envrc` files using a bash subshell. It then detects what environment variables changed, and applies that diff to your current shell (which in your case is zsh). See FAQ #3 here: https://direnv.net/#faq.

**Comment by udl** [comment]
Ah, that was the missing part! Thank you @jfly ! 🙏🏻 
Also thank you for the explanation!
